enableLeaderElection: false
leaderElectionID: null
prometheusAPI: null
host: null
serverAddr: null
metricsAddr: null
probeAddr: null
postgres:
  host: null
  port: null
  dbname: null
  user: null
  password: null
  sslmode: null
  TimeZone: null
auth:
  accessTokenSecret: null
  refreshTokenSecret: null
storage:
  prefix:
    user: null
    account: null
    public: null
  rwxpvcName: null
  roxpvcName: null
workspace:
  namespace: null
  imageNameSpace: null
secrets:
  tlsSecretName: null
  tlsForwardSecretName: null
  imagePullSecretName: ''
imageRegistry:
  server: null
  user: null
  password: null
  project: null
  admin: null
  adminPassword: null
imageBuildTools:
  buildxImage: ''
  nerdctlImage: null
  envdImage: null
smtp:
  host: null
  port: null
  user: null
  password: null
  notify: null
raidsLab:
  ldap:
    userName: null
    password: null
    address: null
    searchDN: null
  openAPI:
    url: null
    chameleonKey: null
    accessToken: null
  enable: false
  uidServerURL: null
schedulerPlugins:
  aijob:
    aijobEn: false
    enableProfiling: true
    profilingTimeout: 120
  spjob:
    spjobEn: false
    predictionServiceAddress: null
