// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAiTask = "ai_tasks"

// AiTask mapped from table <ai_tasks>
type AiTask struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TaskName        string    `gorm:"column:task_name;not null" json:"task_name"`
	Username        string    `gorm:"column:username;not null" json:"username"`
	Namespace       string    `gorm:"column:namespace;not null" json:"namespace"`
	TaskType        string    `gorm:"column:task_type;not null" json:"task_type"`
	CreatedAt       time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	AdmittedAt      time.Time `gorm:"column:admitted_at" json:"admitted_at"`
	StartedAt       time.Time `gorm:"column:started_at" json:"started_at"`
	FinishAt        time.Time `gorm:"column:finish_at" json:"finish_at"`
	Duration        int64     `gorm:"column:duration;not null" json:"duration"`
	Jct             int64     `gorm:"column:jct;not null" json:"jct"`
	Image           string    `gorm:"column:image;not null" json:"image"`
	ResourceRequest string    `gorm:"column:resource_request;not null" json:"resource_request"`
	WorkingDir      string    `gorm:"column:working_dir" json:"working_dir"`
	ShareDirs       string    `gorm:"column:share_dirs" json:"share_dirs"`
	Command         string    `gorm:"column:command" json:"command"`
	Args            string    `gorm:"column:args" json:"args"`
	Slo             int64     `gorm:"column:slo;not null" json:"slo"`
	Status          string    `gorm:"column:status" json:"status"`
	StatusReason    string    `gorm:"column:status_reason" json:"status_reason"`
	Jobname         string    `gorm:"column:jobname" json:"jobname"`
	IsDeleted       bool      `gorm:"column:is_deleted" json:"is_deleted"`
	ProfileStatus   int64     `gorm:"column:profile_status" json:"profile_status"`
	ProfileStat     string    `gorm:"column:profile_stat" json:"profile_stat"`
	EstimatedTime   int64     `gorm:"column:estimated_time" json:"estimated_time"`
	ScheduleInfo    string    `gorm:"column:schedule_info" json:"schedule_info"`
	Token           string    `gorm:"column:token" json:"token"`
	NodePort        int32     `gorm:"column:node_port" json:"node_port"`
	SchedulerName   string    `gorm:"column:scheduler_name" json:"scheduler_name"`
	GpuModel        string    `gorm:"column:gpu_model" json:"gpu_model"`
}

// TableName AiTask's table name
func (*AiTask) TableName() string {
	return TableNameAiTask
}
