// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProject = "projects"

// Project mapped from table <projects>
type Project struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name        string         `gorm:"column:name;comment:项目名" json:"name"`                         // 项目名
	Description string         `gorm:"column:description;comment:项目描述" json:"description"`          // 项目描述
	Namespace   string         `gorm:"column:namespace;comment:命名空间" json:"namespace"`              // 命名空间
	Status      string         `gorm:"column:status;comment:项目状态 (active, inactive)" json:"status"` // 项目状态 (active, inactive)
	Quota       string         `gorm:"column:quota;comment:配额信息" json:"quota"`                      // 配额信息
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
