// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Username  string    `gorm:"column:username;not null" json:"username"`
	Role      string    `gorm:"column:role;not null" json:"role"`
	Password  string    `gorm:"column:password" json:"password"`
	Namespace string    `gorm:"column:namespace;not null" json:"namespace"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
