// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "校验用户身份，生成包含当前用户和项目的 JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handler.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功，返回 JWT Token 和默认个人项目",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_LoginResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "数据库交互错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/admin/aijobs/stats": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "数据库查表count group后返回",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AIJob"
                ],
                "summary": "管理员获取各类任务状态统计情况",
                "responses": {
                    "200": {
                        "description": "状态统计列表",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/admin/aijobs/type": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "查询某类型的全部任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AIJob"
                ],
                "summary": "管理员获取指定类型任务列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分页参数",
                        "name": "page_index",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "筛选、排序参数",
                        "name": "taskType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "总数和jobs数组",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/admin/aijobs/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "检查用户id获取指定id的job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AIJob"
                ],
                "summary": "用户获取指定任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "job id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回任务结构体",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete an AI job by its unique identifier.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AIJob"
                ],
                "summary": "Delete an AIJob by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "AI job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/admin/labels": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "创建标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "label"
                ],
                "summary": "创建标签",
                "parameters": [
                    {
                        "description": "创建标签",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateLabelReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回",
                        "schema": {
                            "$ref": "#/definitions/response.Response-array_model_Label"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/admin/labels/{id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "label"
                ],
                "summary": "更新标签",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新标签",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateLabelReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回",
                        "schema": {
                            "$ref": "#/definitions/response.Response-string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "根据ID删除标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "label"
                ],
                "summary": "删除标签",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回",
                        "schema": {
                            "$ref": "#/definitions/response.Response-string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/admin/projects": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取所有项目的摘要信息，支持筛选条件、分页和排序",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "获取所有项目",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "筛选、排序参数",
                        "name": "is_personal",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name_like",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "x-enum-varnames": [
                            "Asc",
                            "Desc"
                        ],
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "order_col",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页参数",
                        "name": "page_index",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Status is a uint8 type",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "项目列表",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_ListAllResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/admin/users": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "列出用户信息（包含私人配额）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "列出用户信息",
                "responses": {
                    "200": {
                        "description": "成功获取用户信息",
                        "schema": {
                            "$ref": "#/definitions/response.Response-array_handler_UserResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/admin/users/{name}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response-string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/admin/users/{name}/quotas": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新配额",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "更新配额",
                "parameters": [
                    {
                        "type": "string",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新quota",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateQuotaReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功更新配额",
                        "schema": {
                            "$ref": "#/definitions/response.Response-string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/admin/users/{name}/role": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "更新角色",
                "parameters": [
                    {
                        "type": "string",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "role",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新角色成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response-string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/aijobs": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "创建任务并获取任务id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AIJob"
                ],
                "summary": "创建任务",
                "parameters": [
                    {
                        "description": "任务结构体",
                        "name": "CreateJobReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateJobReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/aijobs/getLogs/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "通过指定任务id查询对应pod获取日志",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AIJob"
                ],
                "summary": "获取任务日志",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "日志信息",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/aijobs/getQuota": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "目前只查了数据库确认用户情况，实际直接从sync map获取",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AIJob"
                ],
                "summary": "获取用户当前配额",
                "responses": {
                    "200": {
                        "description": "用户quota描述结构体",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/aijobs/getToken/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "get token from db or pods logs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AIJob"
                ],
                "summary": "get token for access jupyter lab",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "jupyter对应任务id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "端口和token结构体",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/aijobs/jobStats": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "数据库查表count group后返回",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AIJob"
                ],
                "summary": "获取用户各类任务状态统计情况",
                "responses": {
                    "200": {
                        "description": "状态统计列表",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/aijobs/listByStatus": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "根据任务状态和分页要求查询用户下的任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AIJob"
                ],
                "summary": "用户查询任务列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分页参数",
                        "name": "page_index",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "筛选、排序参数",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "总数和任务数组",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/aijobs/updateSLO/{id}": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "根据传入的id和字段值更新任务slo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AIJob"
                ],
                "summary": "更新任务slo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "任务slo",
                        "name": "slo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateTaskReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "null",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/aijobs/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "检查用户id获取指定id的job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AIJob"
                ],
                "summary": "用户获取指定任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "job id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回任务结构体",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete an AI job by its unique identifier.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AIJob"
                ],
                "summary": "Delete an AIJob by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "AI job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/labels": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "show all labels, decs by priority",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "label"
                ],
                "summary": "list labels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-array_model_Label"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/nodes": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "kubectl + prometheus获取节点基本信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Node"
                ],
                "summary": "获取节点基本信息",
                "responses": {
                    "200": {
                        "description": "成功返回值描述，注意这里返回Json字符串，swagger无法准确解析",
                        "schema": {
                            "$ref": "#/definitions/response.Response-string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/nodes/{name}/pod/": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "kubectl + prometheus获取节点Pod信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Node"
                ],
                "summary": "获取节点Pod信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点名称",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回值描述",
                        "schema": {
                            "$ref": "#/definitions/response.Response-payload_ClusterNodePodInfo"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/projects": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "连接用户项目表和项目表，获取用户的所有项目的摘要信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "获取用户的所有项目",
                "responses": {
                    "200": {
                        "description": "成功返回值描述",
                        "schema": {
                            "$ref": "#/definitions/response.Response-array_payload_ProjectResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "从请求中获取项目名称、描述和配额，以当前用户为管理员，创建一个团队项目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "创建团队项目",
                "parameters": [
                    {
                        "description": "项目信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ProjectCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功创建项目，返回项目ID",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_ProjectCreateResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "项目创建失败，返回错误信息",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/v1/switch": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "读取body中的项目ID，生成新的 JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "类似登录，切换项目并返回新的 JWT Token",
                "parameters": [
                    {
                        "description": "项目ID",
                        "name": "project_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.SwitchProjectReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户上下文",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_LoginResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "其他错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.CreateJobReq": {
            "type": "object",
            "properties": {
                "extra": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "resourceRequest": {
                    "type": "string"
                },
                "taskType": {
                    "type": "string"
                }
            }
        },
        "handler.CreateLabelReq": {
            "type": "object",
            "required": [
                "name",
                "priority",
                "type"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/model.WorkerType"
                }
            }
        },
        "handler.ListAllResp": {
            "type": "object"
        },
        "handler.LoginReq": {
            "type": "object",
            "required": [
                "auth",
                "password",
                "username"
            ],
            "properties": {
                "auth": {
                    "description": "认证方式 [normal, act]",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "handler.LoginResp": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "context": {
                    "$ref": "#/definitions/handler.PlatformContext"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "handler.PlatformContext": {
            "type": "object",
            "properties": {
                "platformRole": {
                    "description": "User role of the platform",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Role"
                        }
                    ]
                },
                "projectID": {
                    "description": "Default Project ID",
                    "type": "integer"
                },
                "projectRole": {
                    "description": "User role of the project",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Role"
                        }
                    ]
                }
            }
        },
        "handler.ProjectCreateReq": {
            "type": "object",
            "required": [
                "description",
                "name",
                "quota"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "quota": {
                    "$ref": "#/definitions/handler.QuotaReq"
                }
            }
        },
        "handler.ProjectCreateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "handler.QuotaReq": {
            "type": "object",
            "required": [
                "cpu",
                "gpu",
                "memory",
                "storage"
            ],
            "properties": {
                "cpu": {
                    "type": "integer"
                },
                "gpu": {
                    "type": "integer"
                },
                "memory": {
                    "type": "integer"
                },
                "storage": {
                    "type": "integer"
                }
            }
        },
        "handler.SwitchProjectReq": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "handler.UpdateLabelReq": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/model.WorkerType"
                }
            }
        },
        "handler.UpdateQuotaReq": {
            "type": "object",
            "properties": {
                "cpu": {
                    "type": "integer"
                },
                "cpuReq": {
                    "type": "integer"
                },
                "extra": {
                    "type": "string"
                },
                "gpu": {
                    "type": "integer"
                },
                "gpuMem": {
                    "type": "integer"
                },
                "gpuMemReq": {
                    "type": "integer"
                },
                "gpuReq": {
                    "type": "integer"
                },
                "job": {
                    "type": "integer"
                },
                "jobReq": {
                    "type": "integer"
                },
                "mem": {
                    "type": "integer"
                },
                "memReq": {
                    "type": "integer"
                },
                "node": {
                    "type": "integer"
                },
                "nodeReq": {
                    "type": "integer"
                },
                "storage": {
                    "type": "integer"
                }
            }
        },
        "handler.UpdateRoleReq": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "role": {
                    "$ref": "#/definitions/model.Role"
                }
            }
        },
        "handler.UpdateTaskReq": {
            "type": "object",
            "required": [
                "slo"
            ],
            "properties": {
                "slo": {
                    "description": "change the slo of the job",
                    "type": "integer"
                }
            }
        },
        "handler.UserResp": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户ID",
                    "type": "integer"
                },
                "name": {
                    "description": "用户名称",
                    "type": "string"
                },
                "quota": {
                    "description": "私人Quota，包含Job、Node等",
                    "allOf": [
                        {
                            "$ref": "#/definitions/payload.Quota"
                        }
                    ]
                },
                "role": {
                    "description": "用户角色",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Role"
                        }
                    ]
                },
                "status": {
                    "description": "用户状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Status"
                        }
                    ]
                }
            }
        },
        "model.Label": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/model.WorkerType"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Role": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "_",
                "RoleGuest",
                "RoleUser",
                "RoleAdmin"
            ]
        },
        "model.Status": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "StatusActive": "Active status",
                "StatusInactive": "Inactive status",
                "StatusPending": "Pending status, not yet activated"
            },
            "x-enum-varnames": [
                "_",
                "StatusPending",
                "StatusActive",
                "StatusInactive"
            ]
        },
        "model.WorkerType": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-comments": {
                "Nvidia": "Nvidia GPU worker"
            },
            "x-enum-varnames": [
                "_",
                "Nvidia"
            ]
        },
        "payload.ClusterNodePodInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "arch": {
                    "type": "string"
                },
                "containerRuntimeVersion": {
                    "type": "string"
                },
                "isReady": {
                    "type": "boolean"
                },
                "kubeletVersion": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "os": {
                    "type": "string"
                },
                "osVersion": {
                    "type": "string"
                },
                "pods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/payload.Pod"
                    }
                },
                "role": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "payload.Order": {
            "type": "string",
            "enum": [
                "asc",
                "desc"
            ],
            "x-enum-varnames": [
                "Asc",
                "Desc"
            ]
        },
        "payload.Pod": {
            "type": "object",
            "properties": {
                "CPU": {
                    "type": "number"
                },
                "IP": {
                    "type": "string"
                },
                "Mem": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "payload.ProjectResp": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "项目ID",
                    "type": "integer"
                },
                "isPersonal": {
                    "description": "是否为个人项目",
                    "type": "boolean"
                },
                "name": {
                    "description": "项目名称",
                    "type": "string"
                },
                "role": {
                    "description": "用户在项目中的角色",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Role"
                        }
                    ]
                },
                "status": {
                    "description": "项目状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Status"
                        }
                    ]
                }
            }
        },
        "payload.Quota": {
            "type": "object",
            "properties": {
                "cpu": {
                    "type": "integer"
                },
                "cpuReq": {
                    "type": "integer"
                },
                "extra": {
                    "type": "string"
                },
                "gpu": {
                    "type": "integer"
                },
                "gpuMem": {
                    "type": "integer"
                },
                "gpuMemReq": {
                    "type": "integer"
                },
                "gpuReq": {
                    "type": "integer"
                },
                "job": {
                    "type": "integer"
                },
                "jobReq": {
                    "type": "integer"
                },
                "mem": {
                    "type": "integer"
                },
                "memReq": {
                    "type": "integer"
                },
                "node": {
                    "type": "integer"
                },
                "nodeReq": {
                    "type": "integer"
                },
                "storage": {
                    "type": "integer"
                }
            }
        },
        "response.ErrorCode": {
            "type": "integer",
            "enum": [
                0,
                40001,
                40101,
                40102,
                40103,
                40301,
                99999
            ],
            "x-enum-varnames": [
                "OK",
                "InvalidRequest",
                "TokenExpired",
                "UserNotFound",
                "InvalidToken",
                "InvalidRole",
                "NotSpecified"
            ]
        },
        "response.Response-any": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/response.ErrorCode"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.Response-array_handler_UserResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/response.ErrorCode"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.UserResp"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.Response-array_model_Label": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/response.ErrorCode"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Label"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.Response-array_payload_ProjectResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/response.ErrorCode"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/payload.ProjectResp"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.Response-handler_ListAllResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/response.ErrorCode"
                },
                "data": {
                    "$ref": "#/definitions/handler.ListAllResp"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.Response-handler_LoginResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/response.ErrorCode"
                },
                "data": {
                    "$ref": "#/definitions/handler.LoginResp"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.Response-handler_ProjectCreateResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/response.ErrorCode"
                },
                "data": {
                    "$ref": "#/definitions/handler.ProjectCreateResp"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.Response-payload_ClusterNodePodInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/response.ErrorCode"
                },
                "data": {
                    "$ref": "#/definitions/payload.ClusterNodePodInfo"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.Response-string": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/response.ErrorCode"
                },
                "data": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "访问 /login 并获取 TOKEN 后，填入 'Bearer ${TOKEN}' 以访问受保护的接口",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.3.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Crater API",
	Description:      "This is the API server for Crater, a Multi-tenant AI Model Training Platform based on Kubernetes.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
