//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataRelationShip) DeepCopyInto(out *DataRelationShip) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataRelationShip.
func (in *DataRelationShip) DeepCopy() *DataRelationShip {
	if in == nil {
		return nil
	}
	out := new(DataRelationShip)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSet) DeepCopyInto(out *DataSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSet.
func (in *DataSet) DeepCopy() *DataSet {
	if in == nil {
		return nil
	}
	out := new(DataSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSetList) DeepCopyInto(out *DataSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSetList.
func (in *DataSetList) DeepCopy() *DataSetList {
	if in == nil {
		return nil
	}
	out := new(DataSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSetRef) DeepCopyInto(out *DataSetRef) {
	*out = *in
	out.DataSet = in.DataSet
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSetRef.
func (in *DataSetRef) DeepCopy() *DataSetRef {
	if in == nil {
		return nil
	}
	out := new(DataSetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSetSpec) DeepCopyInto(out *DataSetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSetSpec.
func (in *DataSetSpec) DeepCopy() *DataSetSpec {
	if in == nil {
		return nil
	}
	out := new(DataSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSetStatus) DeepCopyInto(out *DataSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSetStatus.
func (in *DataSetStatus) DeepCopy() *DataSetStatus {
	if in == nil {
		return nil
	}
	out := new(DataSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendDLJob) DeepCopyInto(out *RecommendDLJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendDLJob.
func (in *RecommendDLJob) DeepCopy() *RecommendDLJob {
	if in == nil {
		return nil
	}
	out := new(RecommendDLJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecommendDLJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendDLJobList) DeepCopyInto(out *RecommendDLJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RecommendDLJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendDLJobList.
func (in *RecommendDLJobList) DeepCopy() *RecommendDLJobList {
	if in == nil {
		return nil
	}
	out := new(RecommendDLJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecommendDLJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendDLJobSpec) DeepCopyInto(out *RecommendDLJobSpec) {
	*out = *in
	if in.DataSets != nil {
		in, out := &in.DataSets, &out.DataSets
		*out = make([]DataSetRef, len(*in))
		copy(*out, *in)
	}
	if in.RelationShips != nil {
		in, out := &in.RelationShips, &out.RelationShips
		*out = make([]DataRelationShip, len(*in))
		copy(*out, *in)
	}
	in.Template.DeepCopyInto(&out.Template)
	if in.VocabularySize != nil {
		in, out := &in.VocabularySize, &out.VocabularySize
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.EmbeddingDim != nil {
		in, out := &in.EmbeddingDim, &out.EmbeddingDim
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.InputTensor != nil {
		in, out := &in.InputTensor, &out.InputTensor
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendDLJobSpec.
func (in *RecommendDLJobSpec) DeepCopy() *RecommendDLJobSpec {
	if in == nil {
		return nil
	}
	out := new(RecommendDLJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendDLJobStatus) DeepCopyInto(out *RecommendDLJobStatus) {
	*out = *in
	if in.PodNames != nil {
		in, out := &in.PodNames, &out.PodNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendDLJobStatus.
func (in *RecommendDLJobStatus) DeepCopy() *RecommendDLJobStatus {
	if in == nil {
		return nil
	}
	out := new(RecommendDLJobStatus)
	in.DeepCopyInto(out)
	return out
}
