# Copyright 2025 RAIDS Lab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Push Dependency Images

on:
  push:
    branches: [main]
    paths:
      - "hack/depend-image-dockerfile/**"

env:
  REGISTRY: ghcr.io
  REPOSITORY: raids-lab
  BUILDX_CLIENT: buildx-client
  BUILDX_VERSION: v0.25.0
  ENVD_CLIENT: envd-client
  ENVD_VERSION: v1.2.1
  NERDCTL_CLIENT: nerdctl-client
  NERDCTL_VERSION: v2.1.2

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      buildx-client: ${{ steps.changes.outputs.buildx-client }}
      envd-client: ${{ steps.changes.outputs.envd-client }}
      nerdctl-client: ${{ steps.changes.outputs.nerdctl-client }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            buildx-client:
              - 'hack/depend-image-dockerfile/buildx-client/**'
            envd-client:
              - 'hack/depend-image-dockerfile/envd-client/**'
            nerdctl-client:
              - 'hack/depend-image-dockerfile/nerdctl-client/**'

  build-buildx-client:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.buildx-client == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta for buildx-client
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.BUILDX_CLIENT }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ env.BUILDX_VERSION }}

      - name: Build and push buildx-client image
        uses: docker/build-push-action@v6
        with:
          context: hack/depend-image-dockerfile/${{ env.BUILDX_CLIENT }}
          file: hack/depend-image-dockerfile/${{ env.BUILDX_CLIENT }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-envd-client:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.envd-client == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta for envd-client
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.ENVD_CLIENT }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ env.ENVD_VERSION }}

      - name: Build and push envd-client image
        uses: docker/build-push-action@v6
        with:
          context: hack/depend-image-dockerfile/${{ env.ENVD_CLIENT }}
          file: hack/depend-image-dockerfile/${{ env.ENVD_CLIENT }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-nerdctl-client:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.nerdctl-client == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta for nerdctl-client
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.NERDCTL_CLIENT }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ env.NERDCTL_VERSION }}

      - name: Build and push nerdctl-client image
        uses: docker/build-push-action@v6
        with:
          context: hack/depend-image-dockerfile/${{ env.NERDCTL_CLIENT }}
          file: hack/depend-image-dockerfile/${{ env.NERDCTL_CLIENT }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  cleanup:
    runs-on: ubuntu-latest
    needs: [build-buildx-client, build-envd-client, build-nerdctl-client]
    if: always() && (needs.build-buildx-client.result == 'success' || needs.build-envd-client.result == 'success' || needs.build-nerdctl-client.result == 'success')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clean up old images
        uses: quartx-analytics/ghcr-cleaner@v1
        with:
          owner-type: org
          token: ${{ secrets.PAT_TOKEN }}
          repository-owner: ${{ github.repository_owner }}
          package-name: ${{ env.BUILDX_CLIENT }}
          delete-untagged: true
          keep-at-most: 5
          skip-tags: latest
        continue-on-error: true

      - name: Clean up old envd-client images
        uses: quartx-analytics/ghcr-cleaner@v1
        with:
          owner-type: org
          token: ${{ secrets.PAT_TOKEN }}
          repository-owner: ${{ github.repository_owner }}
          package-name: ${{ env.ENVD_CLIENT }}
          delete-untagged: true
          keep-at-most: 5
          skip-tags: latest
        continue-on-error: true

      - name: Clean up old nerdctl-client images
        uses: quartx-analytics/ghcr-cleaner@v1
        with:
          owner-type: org
          token: ${{ secrets.PAT_TOKEN }}
          repository-owner: ${{ github.repository_owner }}
          package-name: ${{ env.NERDCTL_CLIENT }}
          delete-untagged: true
          keep-at-most: 5
          skip-tags: latest
        continue-on-error: true
